#!/usr/bin/env bash
# Replace the GitHub release body for VERSION with notes generated by
# Claude from the lockfile diff and the latest commit message.
#
# Required env:
#   ANTHROPIC_API_KEY  Claude API key. Step is a no-op if unset.
#   GH_TOKEN           Or a `gh` already authenticated.
#
# Usage: regenerate-notes.sh <version>
set -euo pipefail

VERSION="${1:?usage: $0 <version>}"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
cd "$REPO_ROOT"

if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "No ANTHROPIC_API_KEY set; keeping default release notes."
  exit 0
fi

prev=$(git log --pretty=format:'%H' HEAD^ -- .skill-lock.json 2>/dev/null | head -1 || true)
if [[ -n "$prev" ]]; then
  diff=$(git diff "$prev" HEAD -- .skill-lock.json)
  context_label="Lockfile diff vs previous lockfile-touching commit ($prev)"
else
  diff=$(cat .skill-lock.json)
  context_label="Initial release — full lockfile contents"
fi
msg=$(git log -1 --format='%B' HEAD)

payload=$(jq -n \
  --arg diff "$diff" \
  --arg msg "$msg" \
  --arg ver "$VERSION" \
  --arg label "$context_label" \
  '{
    model: "claude-haiku-4-5",
    max_tokens: 800,
    messages: [{
      role: "user",
      content: ("Write concise release notes for jdevera/dotagents version \($ver).\n\n" +
               "This release stems from a change to `.skill-lock.json`, the lockfile written by the `skills` CLI. " +
               "Each entry under `.skills` is one installed skill: the key is its name, `sourceUrl` is where it came from.\n\n" +
               "Report only what skills were Added / Updated / Removed compared to the prior state. " +
               "Ignore non-skill bookkeeping fields (`version`, `lastSelectedAgents`, `installedAt`, `updatedAt`, `skillFolderHash`). " +
               "Do not invent filenames or fields.\n\n" +
               "Format: a one-sentence summary, then markdown bullet groups under **Added** / **Updated** / **Removed** as relevant. " +
               "Skill names in code spans. No filler, no preamble.\n\n" +
               "Commit message:\n\($msg)\n\n" +
               "\($label) of `.skill-lock.json`:\n```diff\n\($diff)\n```")
    }]
  }')

response=$(curl -sS https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$payload")

notes=$(jq -r '.content[0].text // empty' <<<"$response")
if [[ -z "$notes" ]]; then
  echo "Claude returned empty notes; keeping default release body."
  echo "$response"
  exit 0
fi

printf '%s\n' "$notes" > notes.md
gh release edit "$VERSION" --notes-file notes.md
echo "Release notes regenerated for $VERSION."
